[project]
name = "syara"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.0",
    "fastapi>=0.120.2",
    "google-generativeai>=0.8.5",
    "openai>=2.6.1",
    "uvicorn[standard]>=0.38.0",
]
